#!/bin/bash

W="\e[0;39m"
G="\e[1;32m"

echo -e "
Distro     `cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'`
Kernel     `uname -sr`

Hostname   `hostname` : `hostname -i`

Uptime     `uptime -p`

Updates    $G`apt-get -q -y --ignore-hold --allow-change-held-packages --allow-unauthenticated -s dist-upgrade | /bin/grep  ^Inst | wc -l`
$W"
