#!/bin/bash

output1=$(sudo nordvpn status)
output1a=$(echo "$output1" | sed 's/:[[:space:]]*/:       /')

output2=$(sudo nordvpn settings | grep -e '^Meshnet')
output2a=$(echo "$output2" | sed 's/:[[:space:]]*/:      /')

output3=$(sudo nordvpn settings | grep -e '^DNS')
output3a=$(echo "$output3" | sed 's/:[[:space:]]*/:          /')


echo -e "$output1a
$output2a
$output3a"
